import "./globals.css";
import { Lato } from "next/font/google";
import NextAuthSessionProvider from "./provider/sessionProvider";
import { ThemeProvider } from "../components/theme-provider";

const inter = Lato({ weight: ["900", "400"], subsets: ["latin"] });

export const metadata = {
  title: "SIH Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextAuthSessionProvider>
                <main className="flex-1 overflow-y-auto p-6">
                  {children}
                </main>
          </NextAuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
